"""create property import staging and logs

Revision ID: 12ffb387e11a
Revises: 4c9726cb96d7
Create Date: 2026-09-26 14:31:46.475787

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12ffb387e11a"
down_revision: str | Sequence[str] | None = "4c9726cb96d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "oracle":
        op.execute(sa.schema.CreateSequence(sa.Sequence("import_runs_id_seq")))
        op.execute(sa.schema.CreateSequence(sa.Sequence("imoveis_import_row_id_seq")))
        op.execute(sa.schema.CreateSequence(sa.Sequence("imoveis_import_stg_id_seq")))
    op.create_table(
        "import_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_file", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.Integer(), nullable=False),
        sa.Column("finished_at", sa.Integer(), nullable=True),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("inserted_rows", sa.Integer(), nullable=False),
        sa.Column("updated_rows", sa.Integer(), nullable=False),
        sa.Column("rejected_rows", sa.Integer(), nullable=False),
        sa.Column("duplicate_rows", sa.Integer(), nullable=False),
        sa.Column("reactivated_rows", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "imoveis_import_rows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("numero_imovel", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("detail", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["import_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "line_number", name="uq_imp_row_run_line"),
    )
    op.create_table(
        "imoveis_import_staging",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("line_number", sa.Integer(), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["import_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "line_number", name="uq_imp_stage_run_line"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("imoveis_import_staging")
    op.drop_table("imoveis_import_rows")
    op.drop_table("import_runs")
    if op.get_bind().dialect.name == "oracle":
        op.execute(sa.schema.DropSequence(sa.Sequence("imoveis_import_stg_id_seq")))
        op.execute(sa.schema.DropSequence(sa.Sequence("imoveis_import_row_id_seq")))
        op.execute(sa.schema.DropSequence(sa.Sequence("import_runs_id_seq")))
    # ### end Alembic commands ###
