"""create people table

Revision ID: 33f0acdad1f9
Revises:
Create Date: 2026-09-26 10:41:52.614510

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33f0acdad1f9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pessoas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=200), nullable=False),
        sa.Column(
            "tipo_documento",
            sa.Enum("CPF", "CNPJ", name="tipodocumento", native_enum=False),
            nullable=False,
        ),
        sa.Column("numero", sa.String(length=32), nullable=False),
        sa.Column("contatos", sa.String(length=2000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("numero", name="uq_pessoas_numero"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pessoas")
    # ### end Alembic commands ###
