"""create properties and favorites

Revision ID: 4c9726cb96d7
Revises: d2a3d8b067a6
Create Date: 2026-09-26 14:24:01.197763

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c9726cb96d7"
down_revision: str | Sequence[str] | None = "d2a3d8b067a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "imoveis",
        sa.Column("numero", sa.String(length=64), nullable=False),
        sa.Column("uf", sa.String(length=2), nullable=True),
        sa.Column("cidade", sa.String(length=200), nullable=True),
        sa.Column("bairro", sa.String(length=300), nullable=True),
        sa.Column("endereco", sa.Text(), nullable=True),
        sa.Column("preco", sa.Float(), nullable=True),
        sa.Column("valor_avaliacao", sa.Float(), nullable=True),
        sa.Column("desconto", sa.Float(), nullable=True),
        sa.Column("aceita_financiamento", sa.String(length=20), nullable=True),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("modalidade", sa.String(length=200), nullable=True),
        sa.Column("vendido", sa.Boolean(), nullable=False),
        sa.Column("data_denda", sa.Date(), nullable=True),
        sa.Column("valor_venda", sa.Float(), nullable=True),
        sa.Column("link", sa.Text(), nullable=True),
        sa.Column("link_matricula", sa.String(length=2048), nullable=True),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("numero"),
    )
    op.create_table(
        "favoritos",
        sa.Column("usuario_id", sa.String(length=128), nullable=False),
        sa.Column("numero_imovel", sa.String(length=64), nullable=False),
        sa.Column("imovel_json", sa.Text(), nullable=False),
        sa.Column("favoritado_em", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["numero_imovel"],
            ["imoveis.numero"],
        ),
        sa.PrimaryKeyConstraint("usuario_id", "numero_imovel"),
    )
    op.create_index("ix_favoritos_numero_imovel", "favoritos", ["numero_imovel"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_favoritos_numero_imovel", table_name="favoritos")
    op.drop_table("favoritos")
    op.drop_table("imoveis")
    # ### end Alembic commands ###
