"""allow null optional descriptions

Revision ID: d2a3d8b067a6
Revises: ee8929b84670
Create Date: 2026-09-26 14:16:11.380221

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2a3d8b067a6"
down_revision: str | Sequence[str] | None = "ee8929b84670"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _set_nullable(table_name: str, column_name: str, column_type, nullable: bool) -> None:
    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table(table_name) as batch_op:
            batch_op.alter_column(column_name, existing_type=column_type, nullable=nullable)
    else:
        op.alter_column(
            table_name,
            column_name,
            existing_type=column_type,
            nullable=nullable,
        )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _set_nullable("leiloes", "datas", sa.VARCHAR(length=65), nullable=True)
    _set_nullable("processos", "resumo", sa.CLOB(), nullable=True)
    _set_nullable("processos", "obs", sa.CLOB(), nullable=True)
    _set_nullable("vitrines", "descricao", sa.CLOB(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("UPDATE vitrines SET descricao = ' ' WHERE descricao IS NULL"))
    op.execute(sa.text("UPDATE processos SET obs = ' ' WHERE obs IS NULL"))
    op.execute(sa.text("UPDATE processos SET resumo = ' ' WHERE resumo IS NULL"))
    op.execute(sa.text("UPDATE leiloes SET datas = ' ' WHERE datas IS NULL"))
    _set_nullable("vitrines", "descricao", sa.CLOB(), nullable=False)
    _set_nullable("processos", "obs", sa.CLOB(), nullable=False)
    _set_nullable("processos", "resumo", sa.CLOB(), nullable=False)
    _set_nullable("leiloes", "datas", sa.VARCHAR(length=65), nullable=False)
    # ### end Alembic commands ###
