"""create processes and showcases

Revision ID: ee8929b84670
Revises: f6cc3e2d182a
Create Date: 2026-09-26 14:13:20.555550

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee8929b84670"
down_revision: str | Sequence[str] | None = "f6cc3e2d182a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "oracle":
        op.execute(sa.schema.CreateSequence(sa.Sequence("processos_id_seq")))
        op.execute(sa.schema.CreateSequence(sa.Sequence("vitrines_id_seq")))
    op.create_table(
        "vitrines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=300), nullable=False),
        sa.Column("link", sa.String(length=2048), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("criado_em", sa.Integer(), nullable=False),
        sa.Column("atualizado_em", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "processos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_pessoa", sa.Integer(), nullable=False),
        sa.Column("numero", sa.String(length=100), nullable=False),
        sa.Column("assunto", sa.String(length=500), nullable=False),
        sa.Column("resumo", sa.Text(), nullable=False),
        sa.Column("valor", sa.Float(), nullable=False),
        sa.Column("obs", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_pessoa"],
            ["pessoas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processos")
    op.drop_table("vitrines")
    if op.get_bind().dialect.name == "oracle":
        op.execute(sa.schema.DropSequence(sa.Sequence("vitrines_id_seq")))
        op.execute(sa.schema.DropSequence(sa.Sequence("processos_id_seq")))
    # ### end Alembic commands ###
