"""create auctions and files

Revision ID: f6cc3e2d182a
Revises: 33f0acdad1f9
Create Date: 2026-09-26 13:59:18.291934

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6cc3e2d182a"
down_revision: str | Sequence[str] | None = "33f0acdad1f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "oracle":
        op.execute(sa.schema.CreateSequence(sa.Sequence("pessoas_id_seq")))
        op.execute(sa.schema.CreateSequence(sa.Sequence("leiloes_id_seq")))
        op.execute(sa.schema.CreateSequence(sa.Sequence("arquivos_id_seq")))
    op.create_table(
        "leiloes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=300), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "CASA",
                "APARTAMENTO",
                "TERRENO",
                "VEICULO",
                "MOTO",
                name="tipoleilao",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("url_matricula", sa.String(length=2048), nullable=True),
        sa.Column("id_proprietario", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(length=2048), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("cidade", sa.String(length=200), nullable=False),
        sa.Column("estado", sa.String(length=2), nullable=False),
        sa.Column("id_orgao_origem", sa.Integer(), nullable=False),
        sa.Column("datas", sa.String(length=65), nullable=False),
        sa.Column("criado_em", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id_orgao_origem"], ["pessoas.id"]),
        sa.ForeignKeyConstraint(["id_proprietario"], ["pessoas.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "arquivos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=300), nullable=False),
        sa.Column("link", sa.String(length=2048), nullable=False),
        sa.Column("leilao_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["leilao_id"], ["leiloes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("arquivos")
    op.drop_table("leiloes")
    if op.get_bind().dialect.name == "oracle":
        op.execute(sa.schema.DropSequence(sa.Sequence("arquivos_id_seq")))
        op.execute(sa.schema.DropSequence(sa.Sequence("leiloes_id_seq")))
        op.execute(sa.schema.DropSequence(sa.Sequence("pessoas_id_seq")))
    # ### end Alembic commands ###
